### ISSUE TITLE
lint --fix messes up template

### ISSUE THREAD

**Issue by dereklin** [mgechev/tslint-angular#1]
When I run npm run lint -- --fix
This
```
<h1>
  {{name}}
</h1>
```
is turned into this:
```
<h1>
 {{ {nam }}}
</h1>
```
Here is my repo: https://github.com/dereklin/nx-demo-jest/tree/try-tslint-config
The template is at: https://github.com/dereklin/nx-demo-jest/blob/try-tslint-config/apps/app1/src/app/feature1/feature1.component.html

**Comment by mgechev** [comment]
Thanks for the files!

**Comment by mgechev** [comment]
Moved to codelyzer.
