### ISSUE TITLE
Support for Angular 10

### ISSUE THREAD

**Issue by RoopanV** [mgechev/tslint-angular#19]
Hi,
    Currently facing peer dependency facing waring while building the code. Support for angular 10 will be much appreciated

npm WARN tslint-angular@3.0.2 requires a peer of codelyzer@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-angular@3.0.2 requires a peer of tslint@^5.16.0 but none is installed. You must install peer dependencies yourself.

**Comment by mgechev** [comment]
This should be fixed now. Thanks for reporting!
