### ISSUE TITLE
Allowed console.log

### ISSUE THREAD

**Issue by djhojd** [mgechev/tslint-angular#8]
I was wondering why is `console.log` not included in the list?
```
"no-console": [true, "debug", "info", "time", "timeEnd", "trace"],
```
Or even better, why not just
```
"no-console": true,
```
I think that if someone needs to leave a `console` in their code that should be their own custom rule overwrite and not a default.

**Comment by mgechev** [comment]
That's a great point! Currently, this config is blindly following the Angular CLI.

I'd prefer to enable the use of the `console` object. If developers don't want it as part of their production build, it's easy to strip it at build time.
